version: "3"

services:
  # MySQL database
  db:
    image: mysql:latest
    container_name: db
    networks:
      - hellodevops-net
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password

  # RabbitMQ
  mq:
    image: rabbitmq:3
    container_name: mq
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    networks:
      - hellodevops-net
    ports:
      - "5672:5672"

  # hello-node application
  hello-node:
    build: ../hello-node
    volumes:
      - ../hello-node:/opt/hello-node
    container_name: node-app
    networks:
      - hellodevops-net
    ports:
      - "9443:9443"
    restart: on-failure
    depends_on:
      - "db"
      - "mq"
    environment:
      RABBITMQ_HOST: mq
      MYSQL_HOST: db
      MYSQL_PASSWORD: password

  # hello-python application
  hello-python:
    build: ../hello-python
    volumes:
      - ../hello-python:/opt/hello-python
    container_name: python-app
    networks:
      - hellodevops-net
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: mq

networks:
  hellodevops-net:
    driver: bridge
